# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Weekly Smoke tests

on:     
  schedule:
    - cron: '00 6 * * MON'
    
  workflow_dispatch:

env:
  ALLURE_RESULTS: target/allure-results
  ALLURE_REPORT: target/allure-report
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Smoke tests, build No. ${{ github.run_number }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
        
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Build with Maven
      env:
        ADMIN_PASSWORD: ${{ secrets.AUTOTEST_ADMIN_PWD }}
      run: mvn -Dtestng.threads.count=5 -Dgroups=Smoke -DisHeadless=true -DadminPassword=$ADMIN_PASSWORD --file pom.xml clean test
      
    - name: Allure Report action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: ${{ env.ALLURE_RESULTS }}
        gh_pages: gh-pages
        allure_report: ${{ env.ALLURE_REPORT }}
        allure_history: allure-history

    - name: Attach artifact of Allure Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report-run-${{ github.run_number }}
        path: ${{ env.ALLURE_REPORT }}
        retention-days: 7
          
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
